# IMDB Top 1000 Movies — Analysis

- Exploring, cleaning, and analysing the IMDB Top 1000 movies dataset with `pandas` and `numpy`.

## Dataset: IMDB Top 1000 Movies

| Column | Description |
|---|---|
| `Poster_Link` | URL to the movie's poster image |
| `Series_Title` | Title of the movie |
| `Released_Year` | Year the movie was released |
| `Certificate` | Age/content rating (e.g., U, A, PG-13, R) |
| `Runtime` | Movie duration (e.g., "142 min") |
| `Genre` | One or more genres, comma-separated (e.g., "Crime, Drama") |
| `IMDB_Rating` | IMDB user rating out of 10 |
| `Overview` | Short plot summary |
| `Meta_score` | Metacritic score out of 100 |
| `Director` | Movie director |
| `Star1` – `Star4` | Lead actors, in billing order |
| `No_of_Votes` | Number of IMDB user votes the rating is based on |
| `Gross` | Box office gross revenue (USD, comma-formatted string) |

# - Data Exploration

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load Dataset

df = pd.read_csv('dataset\imdb_top_1000.csv')
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

### 1. Check Data Types

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

### 2. Check Duplicates

In [4]:
# df[df.duplicated()]

df.duplicated().sum()

0

### 3.1. Summary statistics for Numerical columns

In [5]:
df.describe().round(2)

       IMDB_Rating  Meta_score  No_of_Votes
count      1000.00      843.00      1000.00
mean          7.95       77.97    273692.91
std           0.28       12.38    327372.70
min           7.60       28.00     25088.00
25%           7.70       70.00     55526.25
50%           7.90       79.00    138548.50
75%           8.10       87.00    374161.25
max           9.30      100.00   2343110.00

### 3.2  Summary statistics for Categorical columns

In [6]:
df.describe(include= ['object'])

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,Overview,Director,Star1,Star2,Star3,Star4,Gross
count,1000,1000,1000,899,1000,1000,1000,1000,1000,1000,1000,1000,831
unique,1000,999,100,16,140,202,1000,548,660,841,891,939,823
top,https://m.media-amazon.com/images/M/MV5BMDFkYT...,Drishyam,2014,U,100 min,Drama,Two imprisoned men bond over a number of years...,Alfred Hitchcock,Tom Hanks,Emma Watson,Rupert Grint,Michael Caine,"4,360,000"
freq,1,2,32,234,23,85,1,14,12,7,5,4,5

### 4. Check missing Values

In [7]:
# Check missing values by (count & percentage)

missing = pd.DataFrame({
    'count' : df.isna().sum(), 
    'percentage' : (df.isna().mean() * 100) 
})

missing[missing['count'] > 0]. sort_values(by= 'count', ascending= False)

             count  percentage
Gross          169        16.9
Meta_score     157        15.7
Certificate    101        10.1

# - Data Cleaning

### - Drop unnecessary Columns

In [8]:
# Poster_Link, 	Overview >> not needed for analysis

df.drop(['Poster_Link', 'Overview'], axis= 1, inplace= True)

### - Investigate `Drishyam` column Series_Title
    - Drishyam are same saries title

In [9]:
# same series title - kept two rows 

df[df['Series_Title'] == 'Drishyam']

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
87,Drishyam,2013,U,160 min,"Crime, Drama, Thriller",8.3,NaN,Jeethu Joseph,Mohanlal,Meena,Asha Sharath,Ansiba,30722,NaN
136,Drishyam,2015,UA,163 min,"Crime, Drama, Mystery",8.2,NaN,Nishikant Kamat,Ajay Devgn,Shriya Saran,Tabu,Rajat Kapoor,70367,"739,478"

##  in depth check for categorical columns

In [10]:
# Extract categorical columns names

categ_cols = df.select_dtypes(include= 'object').columns
categ_cols

Index(['Series_Title', 'Released_Year', 'Certificate', 'Runtime', 'Genre',
       'Director', 'Star1', 'Star2', 'Star3', 'Star4', 'Gross'],
      dtype='object')

In [11]:
for col in categ_cols:
    print(col)
    print(df[col].nunique())
    print('---------------')
    print(df[col].unique())
    print('-' * 50)

Series_Title
999
---------------
['The Shawshank Redemption' 'The Godfather' 'The Dark Knight'
 'The Godfather: Part II' '12 Angry Men'
 'The Lord of the Rings: The Return of the King' 'Pulp Fiction'
 "Schindler's List" 'Inception' 'Fight Club'
 'The Lord of the Rings: The Fellowship of the Ring' 'Forrest Gump'
 'Il buono, il brutto, il cattivo' 'The Lord of the Rings: The Two Towers'
 'The Matrix' 'Goodfellas'
 'Star Wars: Episode V - The Empire Strikes Back'
 "One Flew Over the Cuckoo's Nest" 'Hamilton' 'Gisaengchung'
 'Soorarai Pottru' 'Interstellar' 'Cidade de Deus'
 'Sen to Chihiro no kamikakushi' 'Saving Private Ryan' 'The Green Mile'
 'La vita è bella' 'Se7en' 'The Silence of the Lambs' 'Star Wars'
 'Seppuku' 'Shichinin no samurai' "It's a Wonderful Life" 'Joker'
 'Whiplash' 'The Intouchables' 'The Prestige' 'The Departed' 'The Pianist'
 'Gladiator' 'American History X' 'The Usual Suspects' 'Léon'
 'The Lion King' 'Terminator 2: Judgment Day' 'Nuovo Cinema Paradiso'
 'Hotaru no haka' 'Back to the Future' 'Once Upon a Time in the West'
 'Psycho' 'Casablanca' 'Modern Times' 'City Lights' 'Capharnaüm'
 'Ayla: The Daughter of War' 'Vikram Vedha' 'Kimi no na wa.' 'Dangal'
 'Spider-Man: Into the Spider-Verse' 'Avengers: Endgame'
 'Avengers: Infinity War' 'Coco' 'Django Unchained'
 'The Dark Knight Rises' '3 Idiots' 'Taare Zameen Par' 'WALL·E'
 'The Lives of Others' 'Oldeuboi' 'Memento' 'Mononoke-hime'
 'Once Upon a Time in America' 'Raiders of the Lost Ark' 'The Shining'
 'Apocalypse Now' 'Alien' 'Anand' 'Tengoku to jigoku'
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb'
 'Witness for the Prosecution' 'Paths of Glory' 'Rear Window'
 'Sunset Blvd.' 'The Great Dictator' '1917' 'Tumbbad' 'Andhadhun'
 'Drishyam' 'Jagten' 'Jodaeiye Nader az Simin' 'Incendies'
 'Miracle in cell NO.7' 'Babam ve Oglum' 'Inglourious Basterds'
 'Eternal Sunshine of the Spotless Mind' 'Amélie' 'Snatch'
 'Requiem for a Dream' 'American Beauty' 'Good Will Hunting'
 'Bacheha-Ye aseman' 'Toy Story' 'Braveheart' 'Reservoir Dogs'
 'Full Metal Jacket' 'Idi i smotri' 'Aliens' 'Amadeus' 'Scarface'
 'Star Wars: Episode VI - Return of the Jedi' 'Das Boot' 'Taxi Driver'
 'The Sting' 'A Clockwork Orange' '2001: A Space Odyssey'
 'Per qualche dollaro in più' 'Lawrence of Arabia' 'The Apartment'
 'North by Northwest' 'Vertigo' "Singin' in the Rain" 'Ikiru'
 'Ladri di biciclette' 'Double Indemnity' 'Citizen Kane'
 'M - Eine Stadt sucht einen Mörder' 'Metropolis' 'The Kid' 'Chhichhore'
 'Uri: The Surgical Strike' 'K.G.F: Chapter 1' 'Green Book'
 'Three Billboards Outside Ebbing, Missouri' 'Talvar'
 'Baahubali 2: The Conclusion' 'Klaus' 'Queen' 'Mandariinid'
 'Bhaag Milkha Bhaag' 'Gangs of Wasseypur' 'Udaan' 'Paan Singh Tomar'
 'El secreto de sus ojos' 'Warrior' 'Shutter Island' 'Up'
 'The Wolf of Wall Street' 'Chak De! India' 'There Will Be Blood'
 "Pan's Labyrinth" 'Toy Story 3' 'V for Vendetta' 'Rang De Basanti'
 'Black' 'Batman Begins' 'Swades: We, the People' 'Der Untergang'
 'Hauru no ugoku shiro' 'A Beautiful Mind' 'Hera Pheri'
 'Lock, Stock and Two Smoking Barrels' 'L.A. Confidential' 'Eskiya' 'Heat'
 'Casino' 'Andaz Apna Apna' 'Unforgiven'
 'Indiana Jones and the Last Crusade' 'Dom za vesanje' 'Tonari no Totoro'
 'Die Hard' 'Ran' 'Raging Bull' 'Stalker' 'Höstsonaten' 'The Message'
 'Sholay' 'Monty Python and the Holy Grail' 'The Great Escape'
 'To Kill a Mockingbird' 'Yôjinbô' 'Judgment at Nuremberg'
 'Some Like It Hot' 'Smultronstället' 'Det sjunde inseglet'
 'Du rififi chez les hommes' 'Dial M for Murder' 'Tôkyô monogatari'
 'Rashômon' 'All About Eve' 'The Treasure of the Sierra Madre'
 'To Be or Not to Be' 'The Gold Rush' 'Sherlock Jr.'
 'Portrait de la jeune fille en feu' 'Pink' 'Koe no katachi'
 'Contratiempo' 'Ah-ga-ssi' 'Mommy' 'Haider' 'Logan' 'Room'
 'Relatos salvajes' 'Soul' 'Kis Uykusu' 'PK' 'OMG: Oh My God!'
 'The Grand Budapest Hotel' 'Gone Girl' 'Ôkami kodomo no Ame to Yuki'
 'Hacksaw Ridge' 'Inside Out' 'Barfi!' '12 Years a Slave' 'Rush'
 'Ford v Ferrari' 'Spotlight' 'Song of the Sea' 'Kahaani'
 'Zindagi Na Milegi Dobara' 'Prisoners' 'Mad Max: Fury Road' 'A Wednesday'
 'Gran Torino' 'Harry Potter and the Deathly Hallows: Part 2' 'Okuribito'
 "Hachi: A Dog's Tale" 'Mary and Max' 'How to Train Your Dragon'
 'Into the Wild' 'No Country for Old Men' 'Lage Raho Munna Bhai'
 'Million Dollar Baby' 'Hotel Rwanda' 'Taegukgi hwinalrimyeo'
 'Before Sunset' 'Munna Bhai M.B.B.S.' 'Salinui chueok' 'Dil Chahta Hai'
 'Kill Bill: Vol. 1' 'Finding Nemo' 'Catch Me If You Can' 'Amores perros'
 'Monsters, Inc.'
 'Shin seiki Evangelion Gekijô-ban: Air/Magokoro wo, kimi ni'
 'Lagaan: Once Upon a Time in India' 'The Sixth Sense'
 "La leggenda del pianista sull'oceano" 'The Truman Show'
 'Crna macka, beli macor' 'The Big Lebowski' 'Fa yeung nin wah'
 'Trainspotting' 'Fargo' 'Underground' 'La haine'
 'Dilwale Dulhania Le Jayenge' 'Before Sunrise' 'Trois couleurs: Rouge'
 'Chung Hing sam lam' 'Jurassic Park' 'In the Name of the Father'
 'Ba wang bie ji' 'Dà hóng denglong gaogao guà' 'Dead Poets Society'
 'Stand by Me' 'Platoon' 'Paris, Texas' 'Kaze no tani no Naushika'
 'The Thing' 'Pink Floyd: The Wall' 'Fitzcarraldo' 'Fanny och Alexander'
 'Blade Runner' 'The Elephant Man' 'Life of Brian' 'The Deer Hunter'
 'Rocky' 'Network' 'Barry Lyndon' 'Zerkalo' 'Chinatown' 'Paper Moon'
 'Viskningar och rop' 'Solaris' 'Le samouraï' 'Cool Hand Luke' 'Persona'
 'Andrei Rublev' 'La battaglia di Algeri' 'El ángel exterminador'
 'What Ever Happened to Baby Jane?' 'Sanjuro'
 'The Man Who Shot Liberty Valance' 'Ivanovo detstvo' 'Jungfrukällan'
 'Inherit the Wind' 'Les quatre cents coups' 'Ben-Hur'
 'Kakushi-toride no san-akunin' 'Le notti di Cabiria' 'Kumonosu-jô'
 'The Bridge on the River Kwai' 'On the Waterfront'
 'Le salaire de la peur' 'Ace in the Hole' 'White Heat' 'The Third Man'
 'The Red Shoes' 'The Shop Around the Corner' 'Rebecca'
 'Mr. Smith Goes to Washington' 'Gone with the Wind' 'La Grande Illusion'
 'It Happened One Night' "La passion de Jeanne d'Arc" 'The Circus'
 'Sunrise: A Song of Two Humans' 'The General'
 'Das Cabinet des Dr. Caligari' 'Badhaai ho' 'Togo' 'Airlift'
 'Bajrangi Bhaijaan' 'Baby' 'La La Land' 'Lion' 'The Martian' 'Zootopia'
 'Bãhubali: The Beginning' 'Kaguyahime no monogatari' 'Wonder' 'Gully Boy'
 'Special Chabbis' 'Short Term 12' 'Serbuan maut 2: Berandal'
 'The Imitation Game' 'Guardians of the Galaxy' 'Blade Runner 2049' 'Her'
 'Bohemian Rhapsody' 'The Revenant' 'The Perks of Being a Wallflower'
 'Tropa de Elite 2: O Inimigo Agora é Outro' "The King's Speech"
 'The Help' 'Deadpool' 'Darbareye Elly' 'Dev.D' 'Yip Man'
 'My Name Is Khan' 'Nefes: Vatan Sagolsun' 'Slumdog Millionaire'
 'Black Swan' 'Tropa de Elite' 'The Avengers' 'Persepolis'
 'Dallas Buyers Club' 'The Pursuit of Happyness' 'Blood Diamond'
 'The Bourne Ultimatum' 'Bin-jip' 'Sin City'
 'Le scaphandre et le papillon' 'G.O.R.A.' 'Ratatouille' 'Casino Royale'
 'Kill Bill: Vol. 2' 'Vozvrashchenie'
 'Bom Yeoareum Gaeul Gyeoul Geurigo Bom' 'Mar adentro' 'Cinderella Man'
 'Kal Ho Naa Ho' 'Mou gaan dou'
 'Pirates of the Caribbean: The Curse of the Black Pearl' 'Big Fish'
 'The Incredibles' 'Yeopgijeogin geunyeo' 'Dogville' 'Vizontele'
 'Donnie Darko' 'Magnolia' 'Dancer in the Dark' 'The Straight Story'
 'Pâfekuto burû' 'Festen' 'Central do Brasil' 'The Iron Giant'
 "Knockin' on Heaven's Door" 'Sling Blade' 'Secrets & Lies'
 'Twelve Monkeys' 'Kôkaku Kidôtai' 'The Nightmare Before Christmas'
 'Groundhog Day' 'Bound by Honor' 'Scent of a Woman' 'Aladdin' 'JFK'
 'Beauty and the Beast' 'Dances with Wolves' 'Do the Right Thing'
 'Rain Man' 'Akira' 'The Princess Bride' 'Der Himmel über Berlin'
 'Au revoir les enfants' 'Tenkû no shiro Rapyuta' 'The Terminator'
 'Gandhi' 'Kagemusha' 'Being There' 'Annie Hall' 'Jaws'
 'Dog Day Afternoon' 'Young Frankenstein' 'Papillon' 'The Exorcist'
 'Sleuth' 'The Last Picture Show' 'Fiddler on the Roof' 'Il conformista'
 'Butch Cassidy and the Sundance Kid' "Rosemary's Baby"
 'Planet of the Apes' 'The Graduate' "Who's Afraid of Virginia Woolf?"
 'The Sound of Music' 'Doctor Zhivago' 'Per un pugno di dollari' '8½'
 'Vivre sa vie: Film en douze tableaux' 'The Hustler' 'La dolce vita'
 'Rio Bravo' 'Anatomy of a Murder' 'Touch of Evil' 'Cat on a Hot Tin Roof'
 'Sweet Smell of Success' 'The Killing' 'The Night of the Hunter'
 'La Strada' 'Les diaboliques' 'Stalag 17' 'Roman Holiday'
 'A Streetcar Named Desire' 'In a Lonely Place' 'Kind Hearts and Coronets'
 'Rope' 'Out of the Past' 'Brief Encounter' 'Laura'
 'The Best Years of Our Lives' 'Arsenic and Old Lace' 'The Maltese Falcon'
 'The Grapes of Wrath' 'The Wizard of Oz' 'La règle du jeu' 'The Thin Man'
 'All Quiet on the Western Front' 'Bronenosets Potemkin' 'Knives Out'
 'Dil Bechara' 'Manbiki kazoku' 'Marriage Story' 'Call Me by Your Name'
 'I, Daniel Blake' 'Isle of Dogs' 'Hunt for the Wilderpeople'
 'Captain Fantastic' 'Sing Street' 'Thor: Ragnarok' 'Nightcrawler'
 'Jojo Rabbit' 'Arrival' 'Star Wars: Episode VII - The Force Awakens'
 'Before Midnight' 'X-Men: Days of Future Past' "Bir Zamanlar Anadolu'da"
 'The Artist' 'Edge of Tomorrow' 'Amour' 'The Irishman' 'Un prophète'
 'Moon' 'Låt den rätte komma in' 'District 9' 'The Wrestler' 'Jab We Met'
 'Boyhood' '4 luni, 3 saptamâni si 2 zile' 'Star Trek' 'In Bruges'
 'The Man from Earth' 'Letters from Iwo Jima' 'The Fall' 'Life of Pi'
 'Fantastic Mr. Fox' 'C.R.A.Z.Y.' 'Les choristes' 'Iron Man'
 'Shaun of the Dead' 'Gegen die Wand' 'Mystic River'
 'Harry Potter and the Prisoner of Azkaban' 'Ying xiong' 'Hable con ella'
 "No Man's Land" 'Cowboy Bebop: Tengoku no tobira' 'The Bourne Identity'
 'Nueve reinas' 'Children of Men' 'Almost Famous' 'Mulholland Dr.'
 'Toy Story 2' 'Boogie Nights' 'Mimi wo sumaseba' 'Once Were Warriors'
 'True Romance' 'Trois couleurs: Bleu' 'Jûbê ninpûchô' "Carlito's Way"
 'Edward Scissorhands' 'My Left Foot: The Story of Christy Brown'
 'Crimes and Misdemeanors' 'The Untouchables' 'Hannah and Her Sisters'
 'Brazil' 'This Is Spinal Tap' 'A Christmas Story' 'The Blues Brothers'
 'Manhattan' 'All That Jazz' 'Dawn of the Dead' "All the President's Men"
 'La montaña sagrada' 'Amarcord' 'Le charme discret de la bourgeoisie'
 'Aguirre, der Zorn Gottes' 'Harold and Maude' 'Patton' 'The Wild Bunch'
 'Night of the Living Dead' 'The Lion in Winter'
 'In the Heat of the Night' 'Charade' 'The Manchurian Candidate'
 'Spartacus' "L'avventura" 'Hiroshima mon amour' 'The Ten Commandments'
 'The Searchers' 'East of Eden' 'High Noon' 'Strangers on a Train'
 'Harvey' 'Miracle on 34th Street' 'Notorious' 'The Big Sleep'
 'The Lost Weekend' 'The Philadelphia Story' 'His Girl Friday'
 'The Adventures of Robin Hood' 'A Night at the Opera' 'King Kong'
 'Freaks' 'Nosferatu' 'The Gentlemen' 'Raazi' 'Sound of Metal'
 'Forushande' 'Dunkirk' 'Perfetti sconosciuti' 'Hidden Figures'
 'Paddington 2' 'Udta Punjab' 'Kubo and the Two Strings'
 'M.S. Dhoni: The Untold Story' 'Manchester by the Sea' 'Under sandet'
 'Rogue One' 'Captain America: Civil War' 'The Hateful Eight'
 'Little Women' 'Loving Vincent' 'Pride' 'Le passé' 'La grande bellezza'
 'The Lunchbox' 'Vicky Donor' 'Big Hero 6' 'About Time' 'English Vinglish'
 'Kaze tachinu' 'Toy Story 4' 'La migliore offerta' 'Moonrise Kingdom'
 'How to Train Your Dragon 2' 'The Big Short' 'Kokuhaku'
 'Ang-ma-reul bo-at-da' 'The Girl with the Dragon Tattoo'
 'Captain Phillips' 'Ajeossi' 'Straight Outta Compton' 'Madeo'
 'Chugyeokja' 'The Hobbit: The Desolation of Smaug'
 'Das weiße Band - Eine deutsche Kindergeschichte' 'Män som hatar kvinnor'
 'The Trial of the Chicago 7' 'Druk' 'The Fighter' 'Taken'
 'The Boy in the Striped Pyjamas' 'Once'
 'The Hobbit: An Unexpected Journey' 'Auf der anderen Seite' 'Atonement'
 'Drive' 'American Gangster' 'Avatar' 'Mr. Nobody' 'Apocalypto'
 'Little Miss Sunshine' 'Hot Fuzz' 'The Curious Case of Benjamin Button'
 'Veer-Zaara' 'Adams æbler' 'Pride & Prejudice'
 "The World's Fastest Indian" 'Tôkyô goddofâzâzu' 'Serenity'
 'Walk the Line' 'Ondskan' 'The Notebook' 'Diarios de motocicleta'
 'Lilja 4-ever' 'Les triplettes de Belleville'
 'Gongdong gyeongbi guyeok JSA' 'The Count of Monte Cristo' 'Waking Life'
 'Remember the Titans' 'Wo hu cang long' 'Todo sobre mi madre' 'Cast Away'
 'The Boondock Saints' 'The Insider' 'October Sky' 'Shrek' 'Titanic'
 'Hana-bi' 'Gattaca' 'The Game' 'Breaking the Waves' 'Ed Wood'
 "What's Eating Gilbert Grape" 'Tombstone' 'The Sandlot'
 'The Remains of the Day' 'Naked' 'The Fugitive' 'A Bronx Tale'
 'Batman: Mask of the Phantasm' 'Lat sau san taam' 'Night on Earth'
 'La double vie de Véronique' 'Boyz n the Hood' 'Misery' 'Awakenings'
 'Majo no takkyûbin' 'Glory' 'Dip huet seung hung'
 'Back to the Future Part II' 'Mississippi Burning' 'Predator'
 'Evil Dead II' "Ferris Bueller's Day Off" 'Down by Law' 'The Goonies'
 'The Color Purple' 'The Breakfast Club' 'The Killing Fields'
 'Ghostbusters' 'The Right Stuff' 'The King of Comedy'
 'E.T. the Extra-Terrestrial' 'Kramer vs. Kramer' 'Days of Heaven'
 'The Outlaw Josey Wales' 'The Man Who Would Be King' 'The Conversation'
 'La planète sauvage' 'The Day of the Jackal' 'Badlands' 'Cabaret'
 'Willy Wonka & the Chocolate Factory' 'Midnight Cowboy' 'Wait Until Dark'
 "Guess Who's Coming to Dinner" 'Bonnie and Clyde' 'My Fair Lady'
 'Mary Poppins' 'The Longest Day' 'Jules et Jim' 'The Innocents'
 'À bout de souffle' 'Red River' 'Key Largo' 'To Have and Have Not'
 'Shadow of a Doubt' 'Stagecoach' 'The Lady Vanishes' 'Bringing Up Baby'
 'Bride of Frankenstein' 'Duck Soup' 'Scarface: The Shame of the Nation'
 'Frankenstein' 'Roma' "God's Own Country" 'Deadpool 2' 'Wind River'
 'Get Out' 'Mission: Impossible - Fallout' 'En man som heter Ove'
 'What We Do in the Shadows' 'Omoide no Mânî' 'The Theory of Everything'
 'Kingsman: The Secret Service' 'The Fault in Our Stars'
 'Me and Earl and the Dying Girl'
 'Birdman or (The Unexpected Virtue of Ignorance)' "La vie d'Adèle"
 'Kai po che!' 'The Broken Circle Breakdown'
 'Captain America: The Winter Soldier' 'Rockstar' 'Nebraska'
 'Wreck-It Ralph' 'Le Petit Prince' 'Detachment' 'Midnight in Paris'
 'The Lego Movie' 'Gravity' 'Star Trek Into Darkness'
 'Beasts of No Nation' 'The Social Network' 'X: First Class'
 'The Hangover' 'Skyfall' 'Silver Linings Playbook' 'Argo'
 '(500) Days of Summer' 'Harry Potter and the Deathly Hallows: Part 1'
 'Gake no ue no Ponyo' 'Frost/Nixon' 'Papurika' 'Changeling' 'Flipped'
 'Toki o kakeru shôjo' 'Death Note: Desu nôto' 'This Is England'
 'Ex Machina' 'Efter brylluppet' 'The Last King of Scotland' 'Zodiac'
 'Lucky Number Slevin' 'Joyeux Noël' 'Control' 'Tangled' 'Zwartboek'
 'Brokeback Mountain' '3:10 to Yuma' 'Crash' 'Kung fu'
 'The Bourne Supremacy' 'The Machinist' 'Ray' 'Lost in Translation'
 'Harry Potter and the Goblet of Fire' 'Man on Fire' 'Coraline'
 'The Last Samurai' 'The Magdalene Sisters' 'Good Bye Lenin!' 'In America'
 'I Am Sam' 'Adaptation.' 'Black Hawk Down' 'Road to Perdition'
 'Das Experiment' 'Billy Elliot' 'Hedwig and the Angry Inch'
 "Ocean's Eleven" 'Vampire Hunter D: Bloodlust'
 'O Brother, Where Art Thou?' 'Interstate 60: Episodes of the Road'
 'South Park: Bigger, Longer & Uncut' 'Office Space' 'Happiness'
 'Training Day' 'Rushmore' 'Abre los ojos' 'Being John Malkovich'
 'As Good as It Gets' 'The Fifth Element' 'Le dîner de cons'
 'Donnie Brasco' 'Shine' 'Primal Fear' 'Hamlet' 'A Little Princess'
 'Do lok tin si' 'Il postino' 'Clerks' 'Short Cuts' 'Philadelphia'
 'The Muppet Christmas Carol' 'Malcolm X' 'The Last of the Mohicans'
 'Kurenai no buta' 'Glengarry Glen Ross' 'A Few Good Men'
 'Fried Green Tomatoes' 'Barton Fink' "Miller's Crossing"
 'Who Framed Roger Rabbit' 'Spoorloos' 'Withnail & I' 'The Last Emperor'
 'Empire of the Sun' 'Der Name der Rose' 'Blue Velvet'
 'The Purple Rose of Cairo' 'After Hours' 'Zelig' 'The Verdict'
 'Star Trek II: The Wrath of Khan' 'First Blood' 'Ordinary People'
 'Airplane!' 'Rupan sansei: Kariosutoro no shiro' 'Halloween'
 'Le locataire' 'Love and Death' 'The Taking of Pelham One Two Three'
 'Blazing Saddles' 'Serpico' 'Enter the Dragon' 'Deliverance'
 'The French Connection' 'Dirty Harry' 'Where Eagles Dare'
 'The Odd Couple' 'The Dirty Dozen' 'Belle de jour'
 'A Man for All Seasons' 'Repulsion' 'Zulu' 'Goldfinger' 'The Birds'
 'Cape Fear' 'Peeping Tom' 'The Magnificent Seven' 'Les yeux sans visage'
 'Invasion of the Body Snatchers' 'Rebel Without a Cause'
 'The Ladykillers' 'Sabrina' 'The Quiet Man'
 'The Day the Earth Stood Still' 'The African Queen' 'Gilda' 'Fantasia'
 'The Invisible Man' 'Dark Waters' 'Searching'
 'Once Upon a Time... in Hollywood' 'Nelyubov' 'The Florida Project'
 'Just Mercy' 'Gifted' 'The Peanut Butter Falcon' 'Victoria' 'Mustang'
 'Guardians of the Galaxy Vol. 2' 'Baby Driver' 'Only the Brave'
 'Bridge of Spies' 'Incredibles 2' 'Moana' 'Sicario' 'Creed' 'Leviafan'
 'Hell or High Water' 'Philomena' 'Dawn of the Planet of the Apes'
 'El cuerpo' 'Serbuan maut' 'End of Watch' 'Kari-gurashi no Arietti'
 'A Star Is Born' 'True Grit' 'Hævnen' 'Despicable Me' '50/50' 'Kick-Ass'
 'Celda 211' 'Moneyball' 'La piel que habito' 'Zombieland' 'Die Welle'
 'Sherlock Holmes' 'The Blind Side' 'The Visitor' 'Seven Pounds'
 'Eastern Promises' 'Stardust' 'The Secret of Kells' 'Inside Man'
 'Gone Baby Gone' 'La Vie En Rose' 'Huo Yuan Jia' 'The Illusionist'
 "Dead Man's Shoes" 'Harry Potter and the Half-Blood Prince' '300'
 'Match Point' 'Watchmen' 'Lord of War' 'Saw' 'Synecdoche, New York'
 'Mysterious Skin' "Jeux d'enfants" 'Un long dimanche de fiançailles'
 'The Station Agent' '21 Grams' 'Boksuneun naui geot' 'Finding Neverland'
 '25th Hour' 'The Butterfly Effect' '28 Days Later...' 'Batoru rowaiaru'
 'The Royal Tenenbaums' 'Y tu mamá también'
 "Harry Potter and the Sorcerer's Stone" 'The Others' 'Blow'
 'Enemy at the Gates' 'Minority Report' 'The Hurricane' 'American Psycho'
 'Lola rennt' 'The Thin Red Line' 'Mulan' 'Fear and Loathing in Las Vegas'
 'Funny Games' 'Dark City' 'Sleepers' 'Lost Highway'
 'Sense and Sensibility' 'Die Hard: With a Vengeance' 'Dead Man'
 'The Bridges of Madison County' 'Apollo 13' 'Trois couleurs: Blanc'
 'Falling Down' 'Dazed and Confused' 'My Cousin Vinny' 'Omohide poro poro'
 'Delicatessen' 'Home Alone' 'The Godfather: Part III'
 'When Harry Met Sally...' 'The Little Mermaid'
 'The Naked Gun: From the Files of Police Squad!'
 'Planes, Trains & Automobiles' 'Lethal Weapon' 'Blood Simple'
 'On Golden Pond' 'Mad Max 2' 'The Warriors' 'The Muppet Movie'
 'Escape from Alcatraz' 'Watership Down' 'Midnight Express'
 'Close Encounters of the Third Kind' 'The Long Goodbye' 'Giù la testa'
 "Kelly's Heroes" 'The Jungle Book' 'Blowup' "A Hard Day's Night"
 "Breakfast at Tiffany's" 'Giant' 'From Here to Eternity' 'Lifeboat'
 'The 39 Steps']
--------------------------------------------------
Released_Year
100
---------------
['1994' '1972' '2008' '1974' '1957' '2003' '1993' '2010' '1999' '2001'
 '1966' '2002' '1990' '1980' '1975' '2020' '2019' '2014' '1998' '1997'
 '1995' '1991' '1977' '1962' '1954' '1946' '2011' '2006' '2000' '1988'
 '1985' '1968' '1960' '1942' '1936' '1931' '2018' '2017' '2016' '2012'
 '2009' '2007' '1984' '1981' '1979' '1971' '1963' '1964' '1950' '1940'
 '2013' '2005' '2004' '1992' '1987' '1986' '1983' '1976' '1973' '1965'
 '1959' '1958' '1952' '1948' '1944' '1941' '1927' '1921' '2015' '1996'
 '1989' '1978' '1961' '1955' '1953' '1925' '1924' '1982' '1967' '1951'
 '1949' '1939' '1937' '1934' '1928' '1926' '1920' '1970' '1969' '1956'
 '1947' '1945' '1930' '1938' '1935' '1933' '1932' '1922' '1943' 'PG']
--------------------------------------------------
Certificate
16
---------------
['A' 'UA' 'U' 'PG-13' 'R' nan 'PG' 'G' 'Passed' 'TV-14' '16' 'TV-MA'
 'Unrated' 'GP' 'Approved' 'TV-PG' 'U/A']
--------------------------------------------------
Runtime
140
---------------
['142 min' '175 min' '152 min' '202 min' '96 min' '201 min' '154 min'
 '195 min' '148 min' '139 min' '178 min' '161 min' '179 min' '136 min'

### - `Certificate` cleaning
    - Passed - Approved >> kept
    - UA - U/A >> merge

In [12]:
# Passed - Approved >> kept

df['Certificate'].value_counts(dropna=False)

Certificate
U           234
A           197
UA          175
R           146
NaN         101
PG-13        43
PG           37
Passed       34
G            12
Approved     11
TV-PG         3
GP            2
TV-14         1
16            1
TV-MA         1
Unrated       1
U/A           1
Name: count, dtype: int64

In [13]:
# UA - U/A >> merge

df['Certificate'].replace({'U/A' : 'UA'}, inplace= True)
df['Certificate'].value_counts(dropna=False)

C:\Users\cpu\AppData\Local\Temp\ipykernel_14044\1270405083.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Certificate'].replace({'U/A' : 'UA'}, inplace= True)

Certificate
U           234
A           197
UA          176
R           146
NaN         101
PG-13        43
PG           37
Passed       34
G            12
Approved     11
TV-PG         3
GP            2
TV-14         1
16            1
TV-MA         1
Unrated       1
Name: count, dtype: int64

### - `Released_Year` cleaning
    - 'PG' to 'year= 1995'

In [14]:
# one row (Apollo 13) has relased year 'PG'

not_year = ~df['Released_Year'].str.isnumeric()
df[not_year]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [15]:
# replace ('PG')'1995'

df.loc[not_year, 'Released_Year'] = '1995'

In [16]:
# for check

df.loc[not_year, 'Released_Year']

966    1995
Name: Released_Year, dtype: object

In [17]:
# for check

df[df['Released_Year'] == 'PG']

Empty DataFrame
Columns: [Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Meta_score, Director, Star1, Star2, Star3, Star4, No_of_Votes, Gross]
Index: []

In [18]:
# convert `Released_Year` from object to int 

df['Released_Year'] = df['Released_Year'].astype(int)

df['Released_Year'].info()          # for check

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Released_Year
Non-Null Count  Dtype
--------------  -----
1000 non-null   int32
dtypes: int32(1)
memory usage: 4.0 KB

### - `Runtime` cleaning
    - remove (' min')

In [19]:
# remove (' min') and convert minutes from object to int

df['Runtime'] = df['Runtime'].str.replace(' min', '').astype(int)

df['Runtime'].info()        # for check

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Runtime
Non-Null Count  Dtype
--------------  -----
1000 non-null   int32
dtypes: int32(1)
memory usage: 4.0 KB

### - `Gross` cleaning
    - remove (',')

In [20]:
# remove (',') and convert thousands from object to float

df['Gross'] = df['Gross'].str.replace(',', '').astype(float)

df['Gross'].info()      # for check

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Gross
Non-Null Count  Dtype
--------------  -----
831 non-null    float64
dtypes: float64(1)
memory usage: 7.9 KB

### - Missing Values
    - `Gross` (16.9%), `Meta_score` (15.7%) and `Certificate` (10.1%) are missing values, 
    left as `NaN` rather than filled, 
    because any filled number would be invented data.

##  in depth check for numerical columns

In [21]:
df.describe().round(2)

,Released_Year,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross
count,1000.00,1000.00,1000.00,843.00,1000.00,8.310000e+02
mean,1991.22,122.89,7.95,77.97,273692.91,6.803475e+07
std,23.29,28.09,0.28,12.38,327372.70,1.097500e+08
min,1920.00,45.00,7.60,28.00,25088.00,1.305000e+03
25%,1976.00,103.00,7.70,70.00,55526.25,3.253559e+06
50%,1999.00,119.00,7.90,79.00,138548.50,2.353089e+07
75%,2009.00,137.00,8.10,87.00,374161.25,8.075089e+07
max,2020.00,321.00,9.30,100.00,2343110.00,9.366622e+08

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   int32
 2   Certificate    899 non-null    object
 3   Runtime        1000 non-null   int32
 4   Genre          1000 non-null   object
 5   IMDB_Rating    1000 non-null   float64
 6   Meta_score     843 non-null    float64
 7   Director       1000 non-null   object
 8   Star1          1000 non-null   object
 9   Star2          1000 non-null   object
 10  Star3          1000 non-null   object
 11  Star4          1000 non-null   object
 12  No_of_Votes    1000 non-null   int64
 13  Gross          831 non-null    float64
dtypes: float64(3), int32(2), int64(1), object(8)
memory usage: 101.7+ KB

# - Data Analysis

### -  Which movie have the Heighst Revenue?

In [23]:
# Star Wars: Episode VII

df[df['Gross'] == df['Gross'].max()][['Series_Title','Released_Year', 'Gross']]

                                   Series_Title  Released_Year        Gross
477  Star Wars: Episode VII - The Force Awakens           2015  936662225.0

In [24]:
df.nlargest(3, 'Gross')[['Series_Title','Released_Year', 'Gross']]

                                   Series_Title  Released_Year        Gross
477  Star Wars: Episode VII - The Force Awakens           2015  936662225.0
59                            Avengers: Endgame           2019  858373000.0
623                                      Avatar           2009  760507625.0

- (Star Wars: Episode VII – The Force Awakens), earned about ($936.7M) is the most, 
followed by (Avengers: Endgame) earned about ($858.4M) and (Avatar) earned about ($760.5M).

### - What is the Average Gross Revenue for movies of the 2000's (2000 --> 2010)

In [25]:
# Filter data first
filter_data = df[df['Released_Year'].between(2000, 2010)]

# Movies released between 2000-2010
print(f'Movies released between 2000-2010 : {len(filter_data)}')

# Average gross revenue
print('Average gross revenue:', round(filter_data['Gross'].mean(), 2))

Movies released between 2000-2010 : 260
Average gross revenue: 73699195.11

- about **$73.7M** per movie, calculated on the 260 movies in this range.

### - What is the Average Run time per Director ?

In [26]:
# Longest average
print('Longest average runtime per director')
display(df.groupby('Director')['Runtime'].mean().sort_values(ascending= False).head())

# Shortest average
print('Shortest average runtime per director')
display(df.groupby('Director')['Runtime'].mean().sort_values(ascending= True).head())

Longest average runtime per director

Director
Kenneth Branagh       242.0
Anurag Kashyap        232.5
Cecil B. DeMille      220.0
Ashutosh Gowariker    217.0
Ramesh Sippy          204.0
Name: Runtime, dtype: float64

Shortest average runtime per director

Director
Buster Keaton     45.0
Tod Browning      64.0
Clyde Bruckman    67.0
Leo McCarey       69.0
James Whale       72.0
Name: Runtime, dtype: float64

-  *Kenneth Branagh* has the longest average runtime (**242 min**) and *Buster Keaton* the shortest (**45 min**).

### - Does users ratings match the metascore ratings ?
        - two ratings (IMDB_Rating - Meta_score)

In [27]:
# IMDB rating

top_IMDB = df.sort_values('IMDB_Rating', ascending= False)[['Series_Title', 'Released_Year','No_of_Votes', 'IMDB_Rating']].head(10)
top_IMDB

,Series_Title,Released_Year,No_of_Votes,IMDB_Rating
0,The Shawshank Redemption,1994,2343110,9.3
1,The Godfather,1972,1620367,9.2
2,The Dark Knight,2008,2303232,9.0
3,The Godfather: Part II,1974,1129952,9.0
4,12 Angry Men,1957,689845,9.0
5,The Lord of the Rings: The Return of the King,2003,1642758,8.9
6,Pulp Fiction,1994,1826188,8.9
7,Schindler's List,1993,1213505,8.9
10,The Lord of the Rings: The Fellowship of the Ring,2001,1661481,8.8
11,Forrest Gump,1994,1809221,8.8

In [28]:
# Meta score

top_Meta = df.sort_values('Meta_score', ascending= False)[['Series_Title', 'Released_Year','No_of_Votes', 'Meta_score']].head(10)
top_Meta

               Series_Title  Released_Year  No_of_Votes  Meta_score
440  Sweet Smell of Success           1957        28137       100.0
81              Rear Window           1954       444074       100.0
50               Casablanca           1942       522093       100.0
260   Trois couleurs: Rouge           1994        90729       100.0
559               Notorious           1946        92306       100.0
274     Fanny och Alexander           1982        57784       100.0
423          Il conformista           1970        27067       100.0
1             The Godfather           1972      1620367       100.0
491                 Boyhood           2014       335533       100.0
124            Citizen Kane           1941       403351       100.0

In [29]:
# Movies with both scores

both = df[['IMDB_Rating', 'Meta_score']].dropna()
print(f'Movies with both scores: {len(both)}')

# Movie in both top list
print('Movie in both top-list:',set(top_IMDB['Series_Title']) & set(top_Meta['Series_Title']))

Movies with both scores: 843
Movie in both top-list: {'The Godfather'}

- The two top-10 lists have **one movie in common** (*The Godfather*) across all 843 movies that have both scores

### - Is there any correlation between numerical columns

In [30]:
df.corr(numeric_only= True).round(2)

,Released_Year,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross
Released_Year,1.00,0.17,-0.13,-0.34,0.24,0.23
Runtime,0.17,1.00,0.24,-0.03,0.17,0.14
IMDB_Rating,-0.13,0.24,1.00,0.27,0.49,0.10
Meta_score,-0.34,-0.03,0.27,1.00,-0.02,-0.03
No_of_Votes,0.24,0.17,0.49,-0.02,1.00,0.57
Gross,0.23,0.14,0.10,-0.03,0.57,1.00

- Strongest: `No_of_Votes` with `Gross` (0.57) and with `IMDB_Rating` (0.49) — movies that more people watch and vote on earn more and rated higher.
- Almost none: `IMDB_Rating` with `Gross` (0.10) — a high rating by itself does not mean a big earn.
- Negative: `Meta_score` with `Released_Year` (−0.34) — newer movies tend to have lower Metascores.

# Conclusions

**Cleaning**
- `Drishyam` appears twice but they are two different films, so kept both.
- `Poster_Link, Overview` are droped, not needed for analysis.
- `U/A` and `UA` Merged label to `UA`.
- `Released_Year`, `Runtime` and `Gross` converted from text to numbers, and fixed one year (*Apollo 13*, `PG` → 1995).
-  `Gross`, `Meta_score` and `Certificate` missing values were left as `NaN`.


**Findings**
- The highest-grossing movie is *Star Wars: Episode VII – The Force Awakens* (≈ $936.7M).
- Movies released 2000–2010 earned about $73.7M on average 260 movies.
- Average runtimes range from 45 min (Buster Keaton) to 242 min (Kenneth Branagh).

**Limitations:** 
- the data is a top-1000 list, so ratings are restricted to 7.6–9.3, and 16.9% of movies have no `Gross`.